
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development
  username: alexey
  password: 54ihanan

test:
  <<: *default
  database: db/test
  username: alexey
  password: 54ihanan

production:
  <<: *default
  database: db/production
